spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://ssafy.shop:3506/notificate?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: bfit
    password: xmrghkfodzld1dnl!
    hikari:
      validation-timeout: 2000
      maximum-pool-size: 50

logging:
  level:
    root: debug

settings:
  cross-origin: "*"

apiPrefix:
  v1