spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://ssafy.shop:3506/notificate?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: bfit
    password: xmrghkfodzld1dnl!
    hikari:
      validation-timeout: 2000
      maximum-pool-size: 50
  jpa:
    database: mysql
logging:
  level:
    root: info

settings:
  cross-origin: "*"

authServer: https://test.auth.ssafy.shop
bizServer: https://test.biz.ssafy.shop
userServer: https://test.user.ssafy.shop
FCMServer : https://fcm.googleapis.com/v1/projects/peeling-onion-80d46/messages:send