server:
  port: 8080

logging:
  level:
    root:
      DEBUG

spring:
  cloud:
    gateway:
      routes:
        #  prod
        - id: alarm-service-prod
          uri: https://alarm.ssafy.shop
          predicates:
            - Host=api.ssafy.shop
            - Path=/alarm/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: auth-service-prod
          uri: https://auth.ssafy.shop
          predicates:
            - Host=api.ssafy.shop
            - Path=/auth/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: biz-service-prod
          uri: https://biz.ssafy.shop
          predicates:
            - Host=api.ssafy.shop
            - Path=/onion/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: field-service-prod
          uri: https://biz.ssafy.shop
          predicates:
            - Host=api.ssafy.shop
            - Path=/field/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: user-service-prod
          uri: https://user.ssafy.shop
          predicates:
            - Host=api.ssafy.shop
            - Path=/user/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        # beta
        - id: alarm-service-test
          uri: https://test.alarm.ssafy.shop
          predicates:
            - Host=test.api.ssafy.shop
            - Path=/alarm/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}\

        - id: auth-service-test
          uri: https://test.auth.ssafy.shop
          predicates:
            - Host=test.api.ssafy.shop
            - Path=/auth/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: biz-service-test
          uri: https://test.biz.ssafy.shop
          predicates:
            - Host=test.api.ssafy.shop
            - Path=/onion/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: field-service-test
          uri: https://test.biz.ssafy.shop
          predicates:
            - Host=test.api.ssafy.shop
            - Path=/field/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: user-service-test
          uri: https://test.user.ssafy.shop
          predicates:
            - Host=test.api.ssafy.shop
            - Path=/user/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
