server:
  port: 8080

zuul:
  routes:
    user:
      path: /user/**
      url: https://test.user.ssafy.shop
    biz:
      path: /biz/**
      url: https://test.biz.ssafy.shop
    alarm:
      path: /alarm/**
      url: https://test.alarm.ssafy.shop
    auth:
      path: /auth/**
      url: https://test.auth.ssafy.shop
  sensitive-headers: Cookie,Set-Cookie
  add-host-header: true
  host:
    max-total-connections: 200
    max-per-route-connections: 20

apiPrefix:
  v1