spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://ssafy.shop:3506/user?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: bfit
    password: xmrghkfodzld1dnl!
    hikari:
      validation-timeout: 2000
      maximum-pool-size: 200
  jpa:
    database: mysql
logging:
  level:
    root: info

settings:
  cross-origin: "*"

authServer: https://auth.ssafy.shop