spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://ssafy.shop:3506/user?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: bfit
    password: xmrghkfodzld1dnl!
    hikari:
      validation-timeout: 2000
      maximum-pool-size: 200
  jpa:
    database: mysql
  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: debug

settings:
  cross-origin: "*"

authServer: https://test.auth.ssafy.shop
bizServer: https://test.biz.ssafy.shop