spring:
  cloud:
    gateway:
      routes:
        - id: user-service-test
          uri: https://test.user.ssafy.shop
          predicates:
            - Host=test.api.ssafy.shop
            - Path=/v1/user/**
          filters:
            - RewritePath=/v1/user/(?<segment>.*), /$\{segment}

        - id: user-service-prod
          uri: https://user.ssafy.shop
          predicates:
            - Host=api.ssafy.shop
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: alarm-service-test
          uri: https://test.alarm.ssafy.shop
          predicates:
            - Host=test.api.ssafy.shop
            - Path=/alarm/**
          filters:
            - RewritePath=/alarm/(?<segment>.*), /$\{segment}

        - id: alarm-service-prod
          uri: https://alarm.ssafy.shop
          predicates:
            - Host=api.ssafy.shop
            - Path=/alarm/**
          filters:
            - RewritePath=/alarm/(?<segment>.*), /$\{segment}

        - id: biz-service-test
          uri: https://test.biz.ssafy.shop
          predicates:
            - Host=test.api.ssafy.shop
            - Path=/onion/**
          filters:
            - RewritePath=/biz/(?<segment>.*), /$\{segment}

        - id: biz-service-prod
          uri: https://biz.ssafy.shop
          predicates:
            - Host=api.ssafy.shop
            - Path=/onion/**
          filters:
            - RewritePath=/biz/(?<segment>.*), /$\{segment}

        - id: auth-service-test
          uri: https://test.auth.ssafy.shop
          predicates:
            - Host=test.api.ssafy.shop
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}

        - id: auth-service-prod
          uri: https://auth.ssafy.shop
          predicates:
            - Host=api.ssafy.shop
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
