// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIm1WmtMjjpgjK6HPG1ooyUYTcT9xJ8x0',
    appId: '1:430647698728:web:05136609fb12afd9c91c1d',
    messagingSenderId: '430647698728',
    projectId: 'peeling-onion-80d46',
    authDomain: 'peeling-onion-80d46.firebaseapp.com',
    storageBucket: 'peeling-onion-80d46.appspot.com',
    measurementId: 'G-9GP0235W3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3CSu3klLUlZuH8RhyPC_5MfYThrrhwik',
    appId: '1:430647698728:android:5ad0de96eaa8dca4c91c1d',
    messagingSenderId: '430647698728',
    projectId: 'peeling-onion-80d46',
    storageBucket: 'peeling-onion-80d46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmjgb8xS9cECY_oVqvxcIFEoMvG1vnsds',
    appId: '1:430647698728:ios:474bff3970cd2e2bc91c1d',
    messagingSenderId: '430647698728',
    projectId: 'peeling-onion-80d46',
    storageBucket: 'peeling-onion-80d46.appspot.com',
    iosClientId: '430647698728-9tbbsc53rkoc9rbgv8aecdscoo60npu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmjgb8xS9cECY_oVqvxcIFEoMvG1vnsds',
    appId: '1:430647698728:ios:5f4daa131b5507bbc91c1d',
    messagingSenderId: '430647698728',
    projectId: 'peeling-onion-80d46',
    storageBucket: 'peeling-onion-80d46.appspot.com',
    iosClientId: '430647698728-i4nj9ra2pm4vjdh9b2tmklu1gr4hs1ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.front.RunnerTests',
  );
}
